#!/usr/bin/env python3

import sys
import nfa

def main(stream=sys.stdin):
    try: 
        w = sys.argv[1]
    except:
        w = ''
    try:
        file = open(sys.argv[2], 'w')
    except:
        file = sys.stdout
    nfa.write(nfa.string_nfa(w), file)

if __name__ == '__main__':
    main()
    


